rebaseMergeAllowed: true
squashMergeAllowed: true
mergeCommitAllowed: false
deleteBranchOnMerge: true
branchProtectionRules:
- pattern: main
  requiredStatusCheckContexts:
    - 'cla/google'
    - 'test'
    - 'snippet-bot check'
    - 'header-check'
  requiredApprovingReviewCount: 1
  requiresCodeOwnerReviews: true
  requiresStrictStatusChecks: false
  isAdminEnforced: false
